marcomusy/vedo

vtkplotter/actors.py

This is useful when getting angle and rotation axis from unit quaternion in vtk: output axis is zero that leads for time being to an error in vtkplotter rotate method (vtkplotter tries to normalize the zero vector)
With patch, we save some computation and prevent from crashing when axis is zero 
Below is the code that show the output we have from vtk with a unit quaternion
import vtk
q = vtk.vtkQuaterniond([1.0,0.0,0.0,0.0])
res = [666.0]*3
angle = q.GetRotationAngleAndAxis(res)
print(res)
print(angle)

Update rotate method in case input angle is zero

---

examples/other/qt_tabs.py
examples/other/qt_window.py
examples/other/qt_window_split.py

@marcomusy 
I've added on-close events to the three qt-examples (qt-window, qt-window-split, qt-window-tabs).
Before applying this fix I had an error-window on closing the qt-tabs example. This is seems to have disappeared after this fix.
Note: checking if this really fixed it is difficult as the error does not always materialize. Probably because it depends on the speed and order of destruction of the objects and interactor.

Added onClose event on qt-examples to fix issue 51

---

vedo/addons.py

Hi Marco, 
I've made a small edit to `Ruler` to add a `scale_factor`. I needed this because in `brainrender` meshes are defined in units of micrometers but I wanted to display distance in `mm`, so I had to scale the distance number computed by `Ruler` accordingly. 
Let me know if you'd like to implement this in `vedo` and if/when you could release a version with it, I'm working on a few additions [to brainrender](https://github.com/BrancoLab/brainrender/issues/104) and would like to have this edited version of `Ruler` in it.

Ruler scale factor

---

vedo/shapes.py

Issue occurs when a point2 is set with a z value but is overwritten to zero in all cases. See below example
```python
import vedo
arc = vedo.shapes.Arc(
center=[2, 2, 3], 
point1=[2, 3, 3],
point2=[3, 2, 3],  # <<< Z value of 3 is overwritten with 0.
invert=False,
c="f",
)
```

fixes bug with arc class

---

vedo/io.py

w and h are not scaled according to settings.screeshotScale while using opencv. This causes video saving to fail.

scale w, h according to settings.screeshotScale while using opencv

---

vedo/utils.py

When you have a large number of iterations, the percentage value reaches 100% too quickly due to rounding calculation and integer conversion.
Keep a float value of the percentage to determine the state of the progress bar and add an integer value for printing.

Add a float percentage value in ProgressBar

---

examples/advanced/measure_curvature.py

I added an example script that shows how to calculate surface curvatures based on the idea of fitting spheres to a local subset of points. The example demonstrates this on a basic shape (ellipsoid) and shows the built-in curvature (Method: Gaussian), the derived curvature from fitting a sphere as well as the residues of the fit process.
There is probably a smoother way to do the visualization, though.
Let me know what you think!
Fixes #610

Add example to calculate and visualize sphere-fitted curvature

---

vedo/plotter.py

Precision needs to be 7 (or even larger) to guarantee a consistent camera when the model coordinates are not centered at (0, 0, 0) and the mode is large. This could happen for plotting geological models with UTM coordinate systems. The default number 4 causes the camera settings to be wildly different each time you reload the model using the camera setting printed out by pressing 'C'.

Increase the precision of camera info.

---

vedo/vtkclasses.py

Hi! This PR adds missing `VTK_HEXAHEDRON` import to fix the following error: 
```
vedo/vedo/ugrid.py", line 74, in __init__
if ct == vtk.VTK_HEXAHEDRON:
AttributeError: module 'vedo.vtkclasses' has no attribute 'VTK_HEXAHEDRON'
```

add VTK_HEXAHEDRON to vedo.vtkcalsses

---

vedo/assembly.py
vedo/base.py
vedo/pointcloud.py
vedo/vtkclasses.py

Hi @marcomusy!
I noticed that grouping meshes with `vedo.Assembly` loses track of scalarbar(s). If that's a desired behavior, feel free to close this PR :) 
This PR includes:
- keep scalarbar(s) alive in `Assembly` by grouping them with `Group`.
- minimal type check for `Assembly.AddPart()`
- update `Assembly.__add__` and `Points.__add__`
- replace `get_meshes()` with `unpack()`, if applicable
Here's a minimal reproducible example / test case:
```python
import vedo
import numpy as np
def offset(mesh, value, axis=False):
"""clone, pointdata, cmap, apply offset, scalarbar, add axis"""
m = mesh.clone()
m.pointdata["random"]  = np.random.random(len(m.points()))
m.cmap(np.random.choice(vedo.colors.cmaps_names), "random")
m.points(m.points() + value)
m.add_scalarbar3d()
if axis:
m += …
```

Keep scalarbar(s) in Assembly

---

docs/documentation.md

The current API documentation still recommends the obsolete ` vedo.Plotter(backend='...') ` method for changing the visualization backend. This fixes it to recommend `settings.default_backend='...' `

Update API Documentation for Changing Backend

---

examples/simulations/aspring2_player.py
vedo/applications.py

Unfortunately, the latest changes brought some bugs, here's a fix for the bugs I could find.
bugs:
- when pressing pause, and then play, duplicate calls to func with the same idx
- if dragging the slider only slightly, duplicate calls to func with the same idx
- is already at `max_value - 1` and pressing play, duplicate call to func with the same idx
- if loop=False, the button would not show as paused when the animation reached the end
- example aspring2_player would make a jump at the beginning, because no calls to update_scene happened until pressing play/forward button
additional changes:
- now also possible to step backwards from `min_value `to `max_value-1` if `loop=True`, so looping in both directions is now allowed
note:
I wish it was possible to have …

Bugfix AnimationPlayer

---

vedo/file_io.py
vedo/pointcloud.py

Hi @marcomusy,
As you deprecated then removed the `pointSize` method, an error appears at the last occurrences that I found in the code.
Simply renamed them to `point_size`.

Change 'pointSize' occurrences to 'point_size'

---

vedo/assembly.py

Hi @marcomusy!
`vedo.Assembly.pickable(<bool>)` sets the property for itself, but pickability of its actors seems to stay untouched. Here's an example:
```python
import vedo
if __name__ == "__main__":
sphere = vedo.Sphere()
axes = vedo.Axes(sphere)
assembly = sphere + axes
assert isinstance(assembly, vedo.Assembly)
assembly.pickable(False)
vedo.show(assembly, mode="TrackballActor")
assert not assembly.pickable()
assembly.pickable(True)
vedo.show(assembly, mode="TrackballActor")
assert assembly.pickable()
```
This won't raise any `AssertionError`, but the meshes were still pickable in `(1)`. This PR extends pickable() to apply the property to its elements.

extend pickable() for Assembly

---

vedo/base.py

This commit fixes two issues:
- When you specify `around` when calling function `_rotatexyz`, the new version of Python would throw an error because `around` is compared directly with a string.
- When you want to run `cut_with_box` function with a `TetMesh` object, the original code would not do anything other than return a `UGrid` object that is not cut with the box. I do not understand the previous fix so I only tried to make the case with a `TetMesh` object work without introducing extra changes.

Minor fix to base.py

---

examples/other/fast_simpl.py

Hello,
This PR follows the discussion in https://github.com/marcomusy/vedo/issues/992
The docstring of the fast-simplification example is updated as signal is transferred from vertices to vertices and not from faces to faces.

Typo in fast simplification example docstring: "faces" -> "vertices"

---

vedo/assembly.py

Hi @marcomusy,
the type check in `vedo.Assembly.__add__` would return False most of the time. Which causes:
```python
a = vedo.Sphere()
b = vedo.Sphere()
c = vedo.Sphere()
d = a + b + c
assert isinstance(d, vedo.Assembly) # fine
assert len(d.actors) == 3 # error
assert len(d.actors) ==2 # fine
assert isinstance(vedo.Mesh(), vedo.vtkclasses.get_class("Prop3D")) # error
assert isinstance(vedo.Points(), vedo.vtkclasses.get_class("Prop3D")) # error
```
In this PR, it checks the type of `obj.actor` instead.

check actor's type in Assembly.__add__

---

vedo/shapes.py

every once in a while the computation for argument of arccos can return a value slightly greater than 1
trap the occurence and simply return the angle of 0 (since the argument to arccos is supposed to be 1 anyway)

minor bug in RoundedLine

---

vedo/settings.py

This PR attempts to mitigate issue #769, that arises due to the Jupyter notebook detection resulting in a false positive when working in an IPython REPL.

Mitigate issue #769: don't set backend to '2d' in IPython REPLs

---

vedo/plotter.py

Hi @marcomusy. I noticed that when printing the camera position, it returns `position` when the docs state it should be `pos`.
This PR changes this from `position` to `pos` to match the docs and helps us stay consistent in brainrender.
I think this is a simple change, but let me know if I've missed anything.

Print position parameter as 'pos'

---

vedo/utils.py

Calling vedo2trimesh() can result in the loss of vertices, as initializing a Trimesh mesh merges close vertices by default (with a tolerance of 1e-8). 
Adding `process=False` prevents this and ensures that the converted mesh does not get altered.

Prevent merging close vertices when converting to Trimesh

---

vedo/mesh.py

Right now if you call cell_normals before calling compute_normals(), it will simply return an empty array.  This is incorrect, and is especially confusing because if a user is new to vedo they will have no way of knowing that there's another function they need to call first, unless they happen to notice it in the API.
This PR has it raise an error instead, thus preventing it from returning the wrong answer while also letting the user know how to fix the problem.

raise an error when calling cell_normals before compute_normals()

---

vedo/mesh.py

This function accepts arguments called `method` and `tol` but didn't state what they did (it was stated that `method` had two possible options but not what they were or what the difference between them was).  This PR adds that information, taken from the VTK documentation and source code.

add documentation to Mesh.boolean()

---

docs/examples_db.js

Hi @marcomusy ,
minor thing I stumbled upon: Link to box cutter was broken. This should fix it :)

fixed broken link to example

---

vedo/file_io.py

Mi @marcomusy 
This PR follows issue #1169 the load functions now accept `pathlib.Path` as input, nothing changed in the behavior of the functions, the paths objects are converted to strings at the beginning.

make load functions compatible with pathlib

---

vedo/plotter.py

While browsing the `Plotter` class docs, I noticed that the example links in the `add_legend_box()` method were broken. I fixed them, no functional changes - only doc link correction.

Fix broken example links in `add_legend_box()` documentation

---

vedo/file_io.py
vedo/vtkclasses.py

- The ome.tif extension is specified at https://ome-model.readthedocs.io/en/stable/ome-tiff/specification.html
- The specialized reader is able to distinguish axes such as time / channel / depth in the tiff stack, which all get smushed together by the plain tiff reader.

Use specialized reader for OME-TIFF files.

---

vedo/shapes.py

Defining Box mesh as bounding box using pos=[xmin,xmax, ymin,ymax, zmin,zmax] does not seem to work properly; however, it **does** work when defined using size or length/width/height. Adjusted the implementation such that the VTK side of the two approaches is the same.
This change does not affect documentation.

Fix: update implementation of Box with bounds input to internally set X/Y/Z lengths
