marcomusy/vedo

vtkplotter/addons.py
=> changed colors of Plotter axis to x=red, y=green, z=blue

README.md
Hi @marcomusy , I updated the conda-forge feedstock. Should be up-to-date again. Stable enough to add it to the readme
=> Added installation from conda to readme

setup.py
Hi,
This PR solves #172. 
Cheers!
Diego
=> Add numpy as dependency in setup.py

examples/basic/silhouette3.py, vedo/pointcloud.py
- Implement orthogonal, oblique and perspective projection on a user defined plane, see issue #191.
- Add a new example ```examples/basic/silhouette3.py```
=> Implement plane projections

examples/basic/mesh_merge_vs_assembly.py
Added a clean version of the example from https://github.com/marcomusy/vedo/issues/222
=> Basic example: mesh merge vs assembly

examples/basic/rgbaImage.py, vedo/picture.py
enable the input of images containing different amounts of channels (…L/LA/RGB/RGBA) for the creation of a Picture object
add an example of partly transparent rgba images
=> modify Picture class to accept L/LA/RGB/RGBA images

vedo/base.py
I think this one change fixes it all :-)
#519
=> fixed invalid zero value for specular-power

docs/logos/embl_logo.py, examples/basic/shadow.py, examples/pyplot/customAxes1.py, examples/pyplot/lorenz.py, examples/simulations/airplane.py, examples/simulations/bloch.py, vedo/base.py, vedo/mesh.py, vedo/plotter.py, vedo/pointcloud.py, vedo/shapes.py
- Implemented multiple shadows discussed at #562
- Matched `addShadow` api with `projectOnPlane`
```python
def addShadow(self, plane=None, point=None, direction=None, clip=False, c=(0.6,0.6,0.6), alpha=1, culling=1)
def projectOnPlane(self, plane='z', point=None, direction=None, clip=False)
```
- Add `contain_points` for `Plane` to check if each point is inside this plane.
=> Implement multiple shadows and match addShadow api with projectOnPlane.

vedo/plotter.py
=> check if interactor is not None before checking GetInitialized()

vedo/shapes.py
.txt regenerates a new poly data from the updated text and updates the actor
to display this new data
Fixes #666
=> Add .text method to Text3D to enable updating the text during an animation

vedo/__init__.py, vedo/utils.py
#error1:  `no moudle named  vtkmodules.all`
error2:  can not found the font files
I have made some modifications, please review and edit
you need update readme file also I think
#682
=> Fatal errors occur when running EXE file which build from vedo

vedo/mesh.py
- The method now allows to set more parameters (direction_matrix, image_size, origin, fg_val, bg_val) upon calling (if they're not provided, it works the same way as the previous version).
- The image filling with foreground voxels is now performed with .Fill() which is faster than a loop in all the points.
=> Mesh.binarize() improvements

vedo/pyplot.py
the links had an extra /example/ directory in the path
=> fix example links for functions in PlotXY class

vedo/file_io.py, vedo/mesh.py
=> Fixes mesh texture gone when plotter saved to npz file

vedo/pointcloud.py
#966 
This adds a check whether a single radius was supplied to the `smooth_mls2d` function or not. If a sequence was supplied, then the respective radius for each point is used for the neighborhood determination and smoothing.
I just tested it in a quick Jupyter notebook and it worked - not sure if there's a more stringent test regiment? Using `pytest` didn't work out of the box :/
=> added support for sequence of radii in smoothing

vedo/utils.py
trimesh.Trimesh.visual may be a TextureVisuals instead of a ColorVisuals.
=> Fix error: AttributeError: 'TextureVisuals' object has no attribute 'vertex_colors'

examples/other/madcad2.py, vedo/utils.py
PR for #976.
Ability to copy across the `vedo.Mesh` pointdata into a `madcad.Mesh` and return it.
=> feat: vedo2madcad

vedo/plotter.py
=> fix some typos in plotter examples

vedo/file_io.py
=> Bug fixes for `load_obj`

vedo/addons.py, vedo/pyplot.py, vedo/visual.py
Hey @marcomusy 
Found a few broken example links and fixed them.
=> fix: several example urls fixed
